name: nomnom
description: "An E-Canteen App."
publish_to: 'none'

version: 0.1.0+1
  
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  google_sign_in: ^6.1.4

  # State Management
  provider: ^6.0.5

  # Animations & Icons
  animate_do: ^3.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Add assets and fonts here if needed
  assets:
    - assets/google_logo.png
    - assets/icon/icon.png
